/*
 * Minimal sdkconfig.h stub for ESP-IDF-free host builds.
 *
 * The real sdkconfig.h is generated by ESP-IDF during `idf.py build`.
 * test/lunar/main/test_lunar.c includes it and guards freertos headers behind
 * CONFIG_IDF_TARGET_LINUX. For a bare host compile we only need that one macro
 * so the device-only code path is excluded.
 */
#pragma once

#define CONFIG_IDF_TARGET_LINUX 1
